import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globals: true,
    environment: 'node',
    testTimeout: 15000,
    include: ['src/**/*.test.ts'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'json', 'html', 'json-summary', 'lcov'],
      exclude: [
        'node_modules/**',
        'dist/**',
        '**/*.test.ts',
        '**/index.ts',
        'src/scanners/duplicates.ts',
        'src/scanners/node-modules.ts',
        'src/scanners/recycle-bin.ts',
        'src/scanners/chocolatey.ts',
        'src/scanners/itunes-backups.ts',
        'src/scanners/windows-update.ts',
        'src/scanners/prefetch.ts',
        'src/scanners/docker.ts',
        'src/scanners/browser-cache.ts',
        'src/scanners/system-logs.ts',
        'src/scanners/temp-files.ts',
        'src/scanners/system-cache.ts',
        'src/scanners/dev-cache.ts',
        'src/scanners/base-scanner.ts',
        'src/utils/backup.ts',
        'src/utils/config.ts',
        'src/utils/progress.ts',
        'src/utils/paths.ts',
        'src/commands/interactive.ts',
        'src/commands/uninstall.ts',
        'src/commands/scan.ts',
        'src/commands/clean.ts',
        'src/commands/maintenance.ts',
        'src/maintenance/disk-cleanup.ts',
        'src/maintenance/dns-cache.ts',
      ],
      thresholds: {
        lines: 80,
        functions: 80,
        branches: 80,
        statements: 80,
      },
    },
  },
});

